// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE44JM2iwAFoNvcYOUMk3wfjBWfFblrgI',
    appId: '1:641447362909:web:1a119d529f5c0c627d28b4',
    messagingSenderId: '641447362909',
    projectId: 'instagram-flutter-clone-dea18',
    authDomain: 'instagram-flutter-clone-dea18.firebaseapp.com',
    databaseURL: 'https://instagram-flutter-clone-dea18-default-rtdb.firebaseio.com',
    storageBucket: 'instagram-flutter-clone-dea18.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrd6ArzD3dC1i3Ztir--UtINRnnyyB1ug',
    appId: '1:641447362909:android:f280c73685e141b07d28b4',
    messagingSenderId: '641447362909',
    projectId: 'instagram-flutter-clone-dea18',
    databaseURL: 'https://instagram-flutter-clone-dea18-default-rtdb.firebaseio.com',
    storageBucket: 'instagram-flutter-clone-dea18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYThb6_K4oQoxstnptYQtoTpDBNAdUaN8',
    appId: '1:641447362909:ios:18f585b2ee598ee07d28b4',
    messagingSenderId: '641447362909',
    projectId: 'instagram-flutter-clone-dea18',
    databaseURL: 'https://instagram-flutter-clone-dea18-default-rtdb.firebaseio.com',
    storageBucket: 'instagram-flutter-clone-dea18.appspot.com',
    iosClientId: '641447362909-8i33pi4n5fs41makbn4daqqemck8372k.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
